import { resolve } from "node:path";
import type { tinyChainSpec } from "@typeberry/lib/config";
import { loadBuildConfig } from "../config/config-loader.js";
import type { ServiceBuildOutput } from "./generate-service-output.js";

/** Directory name for generated config output */
const CONFIG_DIR = "config";

/** Generated test config filename */
const TEST_CONFIG_FILENAME = "jammin.test.config.ts";

/** SDK package name used in generated import statements */
const SDK_PACKAGE_NAME = "@fluffylabs/jammin-sdk";

/**
 * Generated test configuration with service mappings
 */
export interface GeneratedTestConfig {
  services: Record<string, { id: number; name: string }>;
  chainSpec: typeof tinyChainSpec;
}

/**
 * Generate a TypeScript file with test configuration including:
 * - Service ID mappings
 * - ChainSpec configuration
 * - Service names and IDs
 *
 * @param services - Array of service build outputs
 * @param outputPath - Path where to write the generated test config file
 */
export async function generateTestConfigFile(services: ServiceBuildOutput[], outputPath: string): Promise<void> {
  // Create service mapping: service name -> { id, name }
  const serviceMap: Record<string, { id: number; name: string }> = {};

  // Load the config to get service names
  const config = await loadBuildConfig();

  // Match services from config with their IDs from build outputs
  for (let i = 0; i < config.services.length; i++) {
    const service = config.services[i];
    const buildOutput = services[i];
    if (service && buildOutput) {
      serviceMap[service.name] = {
        id: buildOutput.id,
        name: service.name,
      };
    }
  }

  // Generate TypeScript code
  const tsCode = generateTestConfigCode(serviceMap);

  // Write to file
  await Bun.write(outputPath, tsCode);
}

/**
 * Generate test config file in the project's config directory
 * This is typically called after the build command completes
 */
export async function generateTestConfigInProjectDir(
  services: ServiceBuildOutput[],
  projectRoot: string = process.cwd(),
): Promise<string> {
  const configPath = resolve(projectRoot, CONFIG_DIR, TEST_CONFIG_FILENAME);
  await generateTestConfigFile(services, configPath);
  return configPath;
}

/**
 * Generate the TypeScript code for test configuration
 */
export function generateTestConfigCode(serviceMap: Record<string, { id: number; name: string }>): string {
  const serviceEntries = Object.entries(serviceMap)
    .map(([name, config]) => `  ${name}: { id: ServiceId(${config.id}), name: "${config.name}" },`)
    .join("\n");

  return `/**
 * Auto-generated test configuration
 * This file is generated by the jammin build command
 * Do not edit manually
 */
import { config, ServiceId, TestJam } from "${SDK_PACKAGE_NAME}";

/**
 * Type-safe service ID mappings
 * Use these constants instead of hardcoding service IDs in tests
 */
export const SERVICES = {
${serviceEntries}
} as const;

/**
 * Chain specification for tests
 */
export const TEST_CHAIN_SPEC = config.tinyChainSpec;

/**
 * Pre-configured TestJam instance with all services loaded in genesis state
 */
export const testJam = await TestJam.create();
`;
}
